app:
  # å·²å¸®ä½ æ›¿æ¢ä¸ºä½ ç°åœ¨çš„ GitHub Pages åœ°å€
  base_url: "https://inachen1996-hue.github.io/TrendRadar"
  version_check_url: "https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version"
  show_version_update: true # æ§åˆ¶æ˜¾ç¤ºç‰ˆæœ¬æ›´æ–°æç¤ºï¼Œæ”¹æˆ false å°†ä¸æ¥å—æ–°ç‰ˆæœ¬æç¤º

crawler:
  request_interval: 1000 # è¯·æ±‚é—´éš”(æ¯«ç§’)
  enable_crawler: true # æ˜¯å¦å¯ç”¨çˆ¬å–æ–°é—»åŠŸèƒ½ï¼Œfalse æ—¶ç›´æ¥åœæ­¢ç¨‹åº
  use_proxy: false # æ˜¯å¦å¯ç”¨ä»£ç†ï¼Œfalse æ—¶ä¸ºå…³é—­
  default_proxy: "http://127.0.0.1:10086"

# ğŸ”¸ dailyï¼ˆå½“æ—¥æ±‡æ€»æ¨¡å¼ï¼‰ï¼šæ—¥æŠ¥æ€»ç»“
# ğŸ”¸ currentï¼ˆå½“å‰æ¦œå•æ¨¡å¼ï¼‰ï¼šå®æ—¶çƒ­ç‚¹è¿½è¸ª
# ğŸ”¸ incrementalï¼ˆå¢é‡ç›‘æ§æ¨¡å¼ï¼‰ï¼šæœ‰æ–°å¢æ‰æ¨é€ï¼ˆæ¨èè¿½çƒ­ç‚¹ç”¨ï¼‰

report:
  mode: "incremental" # å·²å¸®ä½ æ”¹ä¸ºå¢é‡æ¨¡å¼ï¼Œæœ‰æ–°ç“œæ‰æ¨é€ï¼Œä¸é‡å¤æ‰“æ‰°
  rank_threshold: 5 # æ’åé«˜äº®é˜ˆå€¼

notification:
  enable_notification: true # æ˜¯å¦å¯ç”¨é€šçŸ¥åŠŸèƒ½ï¼Œfalse æ—¶ä¸å‘é€æ‰‹æœºé€šçŸ¥
  message_batch_size: 4000 # æ¶ˆæ¯åˆ†æ‰¹å¤§å°ï¼ˆå­—èŠ‚ï¼‰(è¿™ä¸ªé…ç½®åˆ«åŠ¨)
  batch_send_interval: 1 # æ‰¹æ¬¡å‘é€é—´éš”ï¼ˆç§’ï¼‰
  feishu_message_separator: "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”" # feishu æ¶ˆæ¯åˆ†å‰²çº¿

  silent_push:
    enabled: false  # æ˜¯å¦å¯ç”¨é™é»˜æ¨é€æ¨¡å¼ï¼Œå¦‚æœ trueï¼Œåˆ™å¯ç”¨
    # å› ä¸ºæˆ‘ä»¬ç™½å«–çš„ github æœåŠ¡å™¨æ‰§è¡Œæ—¶é—´ä¸ç¨³å®šï¼Œæ‰€ä»¥æ—¶é—´èŒƒå›´è¦æ ¹æ®å®é™…å°½å¯èƒ½å¤§ä¸€ç‚¹ï¼Œç•™è¶³ 2 å°æ—¶
    # å¦‚æœä½ æƒ³å¯»æ±‚ç¨³å®šçš„æŒ‰æ—¶çš„æ¨é€ï¼Œå»ºè®®éƒ¨ç½²åœ¨ä¸ªäººçš„æœåŠ¡å™¨ä¸Š
    time_range:
      start: "20:00"  # æ¨é€æ—¶é—´èŒƒå›´å¼€å§‹ï¼ˆåŒ—äº¬æ—¶é—´ï¼‰
      end: "22:00"    # æ¨é€æ—¶é—´èŒƒå›´ç»“æŸï¼ˆåŒ—äº¬æ—¶é—´ï¼‰
    once_per_day: true  # æ¯å¤©åœ¨æ—¶é—´èŒƒå›´å†…åªæ¨é€ä¸€æ¬¡ï¼Œå¦‚æœ falseï¼Œåˆ™æ—¶é—´èŒƒå›´å†…æ¯æ¬¡æ‰§è¡Œéƒ½æ¨é€ä¸€æ¬¡
    push_record_retention_days: 7  # æ¨é€è®°å½•ä¿ç•™å¤©æ•°

  # è¯·åŠ¡å¿…å¦¥å–„ä¿ç®¡å¥½ webhooksï¼Œä¸è¦å…¬å¼€
  # å¦‚æœä½ ä»¥ fork çš„æ–¹å¼å°†æœ¬é¡¹ç›®éƒ¨ç½²åœ¨ GitHub ä¸Šï¼Œè¯·å‹¿åœ¨æ­¤å¡«å†™ä»»ä½• webhooksï¼Œè€Œæ˜¯å°† webhooks å¡«å…¥ GitHub Secret
  # ä¸ç„¶è½»åˆ™æ‰‹æœºä¸Šæ”¶åˆ°å¥‡æ€ªçš„å¹¿å‘Šæ¨é€ï¼Œé‡åˆ™å­˜åœ¨ä¸€å®šçš„å®‰å…¨éšæ‚£
  webhooks:
    feishu_url: "" # é£ä¹¦æœºå™¨äººçš„ webhook URL
    dingtalk_url: "" # é’‰é’‰æœºå™¨äººçš„ webhook URL
    wework_url: "" # ä¼ä¸šå¾®ä¿¡æœºå™¨äººçš„ webhook URL
    telegram_bot_token: "" # Telegram Bot Token
    telegram_chat_id: "" # Telegram Chat ID

# ç”¨äºè®©å…³æ³¨åº¦æ›´é«˜çš„æ–°é—»åœ¨æ›´å‰é¢æ˜¾ç¤ºï¼Œåˆèµ·æ¥æ˜¯ 1 å°±è¡Œ
weight:
  rank_weight: 0.6 # æ’åæƒé‡
  frequency_weight: 0.3 # é¢‘æ¬¡æƒé‡
  hotness_weight: 0.1 # çƒ­åº¦æƒé‡

# å¢åŠ æ— èŠçš„å°çŸ¥è¯†
# è¿™é‡Œçš„ name ä½ å¯ä»¥å®šä¹‰ä»»æ„åç§°ï¼Œåªå…·æœ‰æ˜¾ç¤ºä½œç”¨ï¼Œä¸ä¼šå½±å“æ•°æ®çš„å¤„ç†
platforms:
  - id: "douyin"
    name: "æŠ–éŸ³"
